"""
Comprehensive security vendor/product list for autocomplete.
Sourced from market maps, analyst reports, and vendor databases.
Covers EDR, SIEM, cloud, identity, email, network, NDR, vulnerability
management, WAF, SOAR, DLP, GRC, pen testing, IoT/OT, privacy,
DevSecOps, zero trust, browser security, ASM, training, and more.
"""

VENDORS = [
    # --- EDR / XDR / Endpoint Protection ---
    "Acronis Cyber Protect",
    "Bitdefender",
    "Bitdefender GravityZone",
    "BlackBerry",
    "BlackBerry Cylance",
    "Carbon Black",
    "Cisco Secure Endpoint",
    "Comodo",
    "CrowdStrike",
    "CrowdStrike Falcon",
    "Cybereason",
    "Cynet",
    "Cynet 360",
    "Deep Instinct",
    "Elastic Security",
    "Emsisoft",
    "ESET",
    "ESET PROTECT",
    "F-Secure",
    "FortiEDR",
    "Fortinet FortiEDR",
    "Halcyon",
    "Huntress",
    "Kaspersky",
    "Kaspersky Endpoint Security",
    "Malwarebytes",
    "Malwarebytes ThreatDown",
    "McAfee",
    "Microsoft Defender for Endpoint",
    "Microsoft Defender XDR",
    "Norton",
    "Palo Alto Cortex XDR",
    "Cortex XDR",
    "RSA NetWitness XDR",
    "SentinelOne",
    "SentinelOne Singularity",
    "Sophos",
    "Sophos Intercept X",
    "Stellar Cyber",
    "Stellar Cyber Open XDR",
    "Symantec Endpoint Protection",
    "Tanium",
    "Trellix",
    "Trellix Endpoint Security",
    "Trend Micro",
    "Trend Micro Vision One",
    "VMware Carbon Black",
    "WatchGuard",
    "WatchGuard EPDR",
    "WithSecure",
    "WithSecure Elements",

    # --- SIEM ---
    "AlienVault",
    "AlienVault OSSIM",
    "AT&T Cybersecurity",
    "Datadog Security",
    "Devo",
    "Elastic SIEM",
    "Exabeam",
    "Exabeam Fusion",
    "Google Chronicle",
    "Google Chronicle SIEM",
    "Graylog",
    "Hunters",
    "Hunters SIEM",
    "IBM QRadar",
    "IBM QRadar SIEM",
    "LogPoint",
    "LogRhythm",
    "LogRhythm SIEM",
    "ManageEngine Log360",
    "Microsoft Sentinel",
    "New Relic",
    "OSSEC",
    "Panther",
    "Panther SIEM",
    "Rapid7 InsightIDR",
    "Securonix",
    "Splunk",
    "Splunk Enterprise Security",
    "Sumo Logic",
    "Sumo Logic Cloud SIEM",
    "USM Anywhere",
    "Wazuh",

    # --- Cloud Security / CSPM / CWPP / CNAPP ---
    "AccuKnox",
    "Aikido Security",
    "Aqua Security",
    "Aqua CSPM",
    "AWS Security Hub",
    "Bridgecrew",
    "Check Point CloudGuard",
    "CloudGuard",
    "Cyscale",
    "Ermetic",
    "Fidelis Halo",
    "Fugue",
    "Google Cloud Security Command Center",
    "JupiterOne",
    "Lacework",
    "Lightspin",
    "Microsoft Defender for Cloud",
    "Orca Security",
    "Palo Alto Prisma Cloud",
    "Prisma Cloud",
    "Prowler",
    "Qualys TotalCloud",
    "Runecast",
    "ScoutSuite",
    "Snyk Cloud",
    "Sonrai Security",
    "Sysdig",
    "Sysdig Secure",
    "Tenable Cloud Security",
    "Uptycs",
    "Wiz",
    "Zscaler Posture Control",

    # --- Identity / IAM / PAM ---
    "Auth0",
    "Axiad",
    "BeyondTrust",
    "CyberArk",
    "CyberArk Privileged Access",
    "Delinea",
    "Delinea Secret Server",
    "Duo Security",
    "ForgeRock",
    "Foxpass",
    "HashiCorp Vault",
    "IBM Security Verify",
    "Imprivata",
    "JumpCloud",
    "Keeper Security",
    "ManageEngine ADManager",
    "Microsoft Entra ID",
    "miniOrange",
    "Okta",
    "OneIdentity",
    "One Identity",
    "OneLogin",
    "OneSpan",
    "Ping Identity",
    "Ping Identity PingOne",
    "Sailpoint",
    "SailPoint",
    "SailPoint IdentityNow",
    "Saviynt",
    "Silverfort",
    "StrongDM",
    "Teleport",
    "Thales SafeNet",
    "Thycotic",
    "Transmit Security",

    # --- Email Security ---
    "Abnormal Security",
    "Area 1 Security",
    "Avanan",
    "Barracuda",
    "Barracuda Email Security",
    "Cisco Secure Email",
    "Clearswift",
    "Cloudflare Area 1",
    "Cofense",
    "Egress",
    "FireEye Email Security",
    "Forcepoint Email Security",
    "Hornetsecurity",
    "IRONSCALES",
    "Libraesva",
    "Material Security",
    "Mimecast",
    "Perception Point",
    "Proofpoint",
    "Proofpoint Email Protection",
    "Retarus",
    "Sophos Email",
    "SpamTitan",
    "Sublime Security",
    "Symantec Email Security",
    "Tessian",
    "TitanHQ",
    "Trend Micro Email Security",
    "Trustifi",
    "Vade",
    "Vade Secure",
    "Vircom modusGate",
    "Virtru",
    "Zerospam",

    # --- Network Security / Firewall / NGFW ---
    "Barracuda CloudGen Firewall",
    "Cato Networks",
    "Check Point",
    "Check Point Quantum",
    "Cisco",
    "Cisco Firepower",
    "Cisco Meraki",
    "Cloudflare",
    "Cloudflare Magic WAN",
    "Corsa Security",
    "F5",
    "F5 BIG-IP",
    "FireMon",
    "Forcepoint",
    "Forcepoint NGFW",
    "Fortinet",
    "Fortinet FortiGate",
    "Hillstone Networks",
    "Huawei",
    "Juniper",
    "Juniper SRX",
    "Kemp Technologies",
    "Netskope",
    "Palo Alto Networks",
    "Palo Alto Networks NGFW",
    "pfSense",
    "SonicWall",
    "Sophos Firewall",
    "Stormshield",
    "Tufin",
    "Untangle",
    "Versa Networks",
    "WatchGuard Firebox",
    "Zscaler",
    "Zscaler Internet Access",
    "Zyxel",

    # --- NDR (Network Detection & Response) ---
    "Corelight",
    "Darktrace",
    "ExtraHop",
    "ExtraHop Reveal(x)",
    "Fidelis Network",
    "Flowmon",
    "Gigamon",
    "Lumu Technologies",
    "Plixer",
    "Progress Flowmon",
    "Stamus Networks",
    "Vectra AI",
    "Vectra Cognito",
    "Zeek",

    # --- Vulnerability Management ---
    "Arctic Wolf",
    "BeyondTrust Retina",
    "CrowdStrike Falcon Spotlight",
    "Greenbone",
    "InsightVM",
    "Ivanti Neurons",
    "Lansweeper",
    "Nessus",
    "Nexpose",
    "OpenVAS",
    "Qualys",
    "Qualys VMDR",
    "Rapid7",
    "Rapid7 InsightVM",
    "Tenable",
    "Tenable Nessus",
    "Tenable.io",
    "Tripwire",
    "Tripwire IP360",

    # --- Application Security / SAST / DAST / SCA ---
    "Acunetix",
    "Apiiro",
    "AppKnox",
    "Bandit",
    "Bearer",
    "Black Duck",
    "Burp Suite",
    "Checkmarx",
    "Checkmarx SAST",
    "CodeQL",
    "Contrast Security",
    "Coverity",
    "Cycode",
    "Dependabot",
    "Endor Labs",
    "Fortify",
    "GitHub Advanced Security",
    "GitLab Security",
    "GitLab Ultimate Security",
    "Grype",
    "HCL AppScan",
    "Invicti",
    "JFrog Xray",
    "Kodem",
    "Mend",
    "Mend.io",
    "Micro Focus Fortify",
    "Netsparker",
    "Oligo Security",
    "Orca AppSec",
    "OWASP ZAP",
    "OX Security",
    "PortSwigger",
    "Probely",
    "ReversingLabs",
    "Rezilion",
    "Semgrep",
    "ShiftLeft",
    "Snyk",
    "Snyk Code",
    "Snyk Open Source",
    "Socket",
    "SonarQube",
    "SonarCloud",
    "SonarSource",
    "Sonatype",
    "Sonatype Nexus",
    "StackHawk",
    "Synopsys",
    "Veracode",
    "WhiteSource",

    # --- WAF / API Security ---
    "42Crunch",
    "Akamai",
    "Akamai Kona Site Defender",
    "Akamai App & API Protector",
    "AWS WAF",
    "Azure WAF",
    "Cloudflare WAF",
    "Cequence Security",
    "Coraza WAF",
    "F5 Advanced WAF",
    "Fastly Signal Sciences",
    "Google Cloud Armor",
    "Imperva",
    "Imperva WAF",
    "Indusface",
    "Kong",
    "ModSecurity",
    "Noname Security",
    "Prophaze",
    "Radware",
    "Reblaze",
    "Salt Security",
    "Signal Sciences",
    "Traceable AI",
    "ThreatX",
    "Wallarm",
    "Wallarm API Security",

    # --- SOAR ---
    "Blink",
    "Cyware",
    "D3 Security",
    "Fortinet FortiSOAR",
    "Google Siemplify",
    "Hive",
    "IBM Resilient",
    "LogicHub",
    "Palo Alto XSOAR",
    "Cortex XSOAR",
    "Rapid7 InsightConnect",
    "Resolve",
    "ServiceNow Security Operations",
    "Siemplify",
    "Splunk SOAR",
    "Swimlane",
    "TheHive",
    "Tines",
    "Torq",

    # --- DLP (Data Loss Prevention) ---
    "Code42",
    "CoSoSys Endpoint Protector",
    "Digital Guardian",
    "Dtex Systems",
    "Forcepoint DLP",
    "GTB Technologies",
    "McAfee DLP",
    "Microsoft Purview",
    "Microsoft Purview DLP",
    "Netskope DLP",
    "Nightfall AI",
    "Proofpoint DLP",
    "Safetica",
    "Spirion",
    "Symantec DLP",
    "Teramind",
    "Trellix DLP",
    "Zecurion",

    # --- Endpoint Management / UEM ---
    "Automox",
    "Fleet",
    "Hexnode",
    "Ivanti",
    "Jamf",
    "Kandji",
    "ManageEngine Desktop Central",
    "ManageEngine Endpoint Central",
    "Microsoft Intune",
    "Mosyle",
    "NinjaOne",
    "NinjaRMM",
    "VMware Workspace ONE",

    # --- Threat Intelligence ---
    "Anomali",
    "Censys",
    "CrowdStrike Falcon Intelligence",
    "Cyble",
    "DomainTools",
    "EclecticIQ",
    "Flashpoint",
    "GreyNoise",
    "Group-IB",
    "Intel 471",
    "Intel471",
    "Intezer",
    "Mandiant",
    "Mandiant Advantage",
    "MISP",
    "OpenCTI",
    "Recorded Future",
    "RiskIQ",
    "SecurityTrails",
    "Shodan",
    "SOCRadar",
    "SpyCloud",
    "ThreatConnect",
    "ThreatQuotient",
    "ThreatStream",
    "VirusTotal",
    "ZeroFox",

    # --- Backup / Disaster Recovery ---
    "Acronis",
    "Acronis Cyber Protect Cloud",
    "Arcserve",
    "Axcient",
    "Carbonite",
    "Cohesity",
    "Commvault",
    "Datto",
    "Druva",
    "HYCU",
    "Nakivo",
    "Rubrik",
    "Unitrends",
    "Veeam",
    "Veritas",
    "Zerto",

    # --- GRC / Compliance / Audit ---
    "Anecdotes",
    "Archer",
    "AuditBoard",
    "Centraleyes",
    "Compliance.ai",
    "Conveyor",
    "CyberSaint",
    "Diligent",
    "Drata",
    "Galvanize",
    "Hyperproof",
    "Laika",
    "LogicGate",
    "MetricStream",
    "OneTrust",
    "ProcessUnity",
    "Reciprocity ZenGRC",
    "Resolver",
    "Riskonnect",
    "RSA Archer",
    "SafeBase",
    "SAI360",
    "Scytale",
    "Secureframe",
    "ServiceNow GRC",
    "SimpleRisk",
    "Sprinto",
    "StandardFusion",
    "Strike Graph",
    "Thoropass",
    "TrustCloud",
    "Tugboat Logic",
    "Vanta",
    "ZenGRC",

    # --- Pen Testing / Red Team / Breach & Attack Simulation ---
    "AttackIQ",
    "Bugcrowd",
    "Cobalt",
    "Cobalt.io",
    "Core Impact",
    "Cymulate",
    "HackerOne",
    "Horizon3.ai",
    "NodeZero",
    "Mandiant Red Team",
    "Metasploit",
    "NetSPI",
    "Pentera",
    "PlexTrac",
    "Randori",
    "Rapid7 Metasploit",
    "SafeBreach",
    "Scythe",
    "Synack",
    "XM Cyber",

    # --- CASB ---
    "Bitglass",
    "Cisco Cloudlock",
    "Lookout CASB",
    "Lookout",
    "Microsoft Defender for Cloud Apps",
    "Netskope CASB",
    "Skyhigh Security",
    "Zscaler CASB",

    # --- IoT / OT / ICS Security ---
    "ABB Cybersecurity",
    "Armexa",
    "Armis",
    "Claroty",
    "CyberX",
    "Dragos",
    "Forescout",
    "Fortinet OT Security",
    "Honeywell OT Cybersecurity",
    "Industrial Defender",
    "Medigate",
    "Mission Secure",
    "Nozomi Networks",
    "OPSWAT",
    "Otorio",
    "Radiflow",
    "Rockwell Automation Cybersecurity",
    "Schneider Electric Cybersecurity",
    "SCADAfence",
    "Siemens Cybersecurity",
    "TXOne Networks",
    "Verve Industrial",
    "Waterfall Security",

    # --- Privacy / Data Protection ---
    "BigID",
    "DataGrail",
    "Ethyca",
    "Informatica Data Privacy",
    "Ketch",
    "OneTrust Privacy",
    "Osano",
    "Privacera",
    "Securiti",
    "Securiti.ai",
    "TrustArc",
    "Transcend",
    "WireWheel",

    # --- DevSecOps / Container / Kubernetes Security ---
    "Anchore",
    "Aqua Security Trivy",
    "Armo",
    "Bridgecrew Checkov",
    "Chainguard",
    "Falco",
    "Fairwinds",
    "Harness",
    "KubeArmor",
    "Lacework Container Security",
    "NeuVector",
    "Prisma Cloud Compute",
    "Slim.ai",
    "Snyk Container",
    "Sysdig Falco",
    "Trivy",
    "Twistlock",

    # --- Zero Trust / ZTNA / SASE ---
    "Absolute",
    "Akamai Enterprise Application Access",
    "Appgate",
    "Axis Security",
    "Banyan Security",
    "Cato Networks SASE",
    "Cisco Duo",
    "Cloudflare Access",
    "Cloudflare Zero Trust",
    "Forcepoint ONE",
    "Fortinet FortiSASE",
    "Google BeyondCorp",
    "Illumio",
    "InstaSafe",
    "Netskope SASE",
    "Palo Alto Prisma Access",
    "Perimeter 81",
    "Skyhigh Security SASE",
    "Tailscale",
    "Twingate",
    "Versa SASE",
    "VMware SASE",
    "Zscaler Private Access",
    "Zscaler SASE",

    # --- Browser Security ---
    "Authentic8 Silo",
    "Conceal",
    "Island",
    "Menlo Security",
    "Seraphic",
    "Talon Cyber Security",

    # --- Attack Surface Management / Exposure Management ---
    "Assetnote",
    "Bishop Fox Cosmos",
    "BitSight",
    "CyCognito",
    "Halo Security",
    "Mandiant ASM",
    "Microsoft Defender EASM",
    "Palo Alto Cortex Xpanse",
    "Cortex Xpanse",
    "Randori Recon",
    "Rapid7 InsightConnect ASM",
    "RiskIQ (Microsoft)",
    "Runzero",
    "SecurityScorecard",
    "Sevco Security",
    "UpGuard",

    # --- Security Awareness Training ---
    "Cofense PhishMe",
    "CybSafe",
    "Hoxhunt",
    "Infosec IQ",
    "KnowBe4",
    "Living Security",
    "Mimecast Awareness Training",
    "Ninjio",
    "Proofpoint Security Awareness",
    "SANS Security Awareness",
    "Terranova Security",
    "Wombat Security",

    # --- MDR / Managed Security ---
    "Accenture Security",
    "Arctic Wolf MDR",
    "AT&T Managed Security",
    "Binary Defense",
    "BlueVoyant",
    "CrowdStrike Falcon Complete",
    "Deloitte Cyber",
    "eSentire",
    "Expel",
    "IBM Managed Security",
    "KPMG Cyber",
    "Mandiant MDR",
    "Masergy",
    "NTT Security",
    "Optiv",
    "Proficio",
    "PwC Cyber",
    "Red Canary",
    "Secureworks",
    "Secureworks Taegis",
    "Sophos MDR",
    "TrustWave",
    "Trustwave",

    # --- PAM (Privileged Access Management) ---
    "Arcon",
    "BeyondTrust Privileged Access",
    "Centrify",
    "CyberArk PAM",
    "Delinea Privilege Manager",
    "Devolutions",
    "Ekran System",
    "FUDO Security",
    "Iraje",
    "ManageEngine PAM360",
    "Netwrix Privilege Secure",
    "Senhasegura",
    "Thycotic Secret Server",
    "Wallix",
    "Xceedium",

    # --- Secure Access Service Edge / SD-WAN ---
    "Aryaka",
    "Bigleaf Networks",
    "Cisco SD-WAN",
    "Citrix SD-WAN",
    "Cradlepoint",
    "FatPipe",
    "Fortinet FortiSASE",
    "HPE Aruba EdgeConnect",
    "Open Systems SASE",
    "Peplink",
    "Silver Peak",
    "VMware SD-WAN",

    # --- Data Security / Database Security ---
    "Baffle",
    "Comforte AG",
    "Cyera",
    "Dasera",
    "Dig Security",
    "Guardium",
    "Immuta",
    "IBM Guardium",
    "Laminar",
    "Open Raven",
    "Satori",
    "Sotero",
    "Thales CipherTrust",
    "TokenEx",
    "Varonis",
    "Virtru Data Protection",
    "Voltage SecureData",
    "Vormetric",

    # --- Deception Technology ---
    "Acalvio",
    "Attivo Networks",
    "CounterCraft",
    "Fidelis Deception",
    "Illusive Networks",
    "PacketViper",
    "TrapX Security",
    "Zscaler Deception",

    # --- Microsegmentation ---
    "Akamai Guardicore",
    "ColorTokens",
    "Elisity",
    "Guardicore",
    "Illumio Core",
    "TrueFort",
    "VMware NSX",
    "Zero Networks",

    # --- DNS Security ---
    "Akamai DNS Security",
    "BlueCat",
    "Cisco Umbrella",
    "Cloudflare DNS",
    "DNSFilter",
    "EfficientIP",
    "Infoblox",
    "Infoblox BloxOne",
    "Neustar UltraDNS",
    "Nominum",
    "Quad9",
    "Webroot DNS Protection",

    # --- Secure Web Gateway ---
    "Cisco Secure Web Appliance",
    "ContentKeeper",
    "Forcepoint SWG",
    "iboss",
    "McAfee Web Gateway",
    "Menlo Security SWG",
    "Netskope SWG",
    "Symantec Web Security",
    "Zscaler SWG",

    # --- Mobile Security ---
    "Appdome",
    "Corrata",
    "Jamf Protect",
    "Lookout Mobile Security",
    "MobileIron",
    "NowSecure",
    "Pradeo",
    "Samsung Knox",
    "Wandera",
    "Zimperium",

    # --- ITDR (Identity Threat Detection & Response) ---
    "CrowdStrike Falcon Identity Threat Protection",
    "Microsoft Defender for Identity",
    "Oort",
    "Proofpoint Identity Threat Defense",
    "Quest Security",
    "Semperis",
    "Silverfort ITDR",
    "Tenable.ad",

    # --- Supply Chain Security ---
    "Apiiro Supply Chain",
    "Chainguard Images",
    "Cybeats",
    "FOSSA",
    "Legit Security",
    "Lineaje",
    "Manifest",
    "Phylum",
    "Scribe Security",
    "Sigstore",
    "Socket Supply Chain",
    "Tidelift",

    # --- Secrets Management ---
    "1Password",
    "Akeyless",
    "AWS Secrets Manager",
    "Azure Key Vault",
    "BeyondTrust Password Safe",
    "Conjur",
    "CyberArk Conjur",
    "Doppler",
    "Google Secret Manager",
    "HashiCorp Vault Secrets",
    "Keeper Secrets Manager",
    "LastPass",
    "LastPass Business",
    "Passbolt",
    "Thales Luna HSM",

    # --- Security Validation / Continuous Testing ---
    "Bugcrowd Platform",
    "Coalfire",
    "Cobalt Pentest",
    "HackerOne Platform",
    "Horizon3.ai NodeZero",
    "Luta Security",
    "Pentera Platform",
    "Praetorian",
    "Picus Security",
    "Ridge Security",
    "SafeBreach Platform",
    "Synack Red Team",

    # --- Encryption / PKI / Certificate Management ---
    "AppViewX",
    "Comodo Certificate Manager",
    "DigiCert",
    "Entrust",
    "GlobalSign",
    "Keyfactor",
    "Let's Encrypt",
    "PrimeKey",
    "Sectigo",
    "Smallstep",
    "SSL.com",
    "Thales HSM",
    "Venafi",

    # --- Log Management / Observability ---
    "Chronosphere",
    "Cribl",
    "Cribl Stream",
    "Datadog",
    "Grafana",
    "Honeycomb",
    "Humio",
    "LogDNA",
    "Mezmo",
    "Observe Inc",
    "PagerDuty",
    "Papertrail",
    "Scalyr",
    "Seq",
    "Splunk Observability",

    # --- Fraud Prevention / Bot Management ---
    "Akamai Bot Manager",
    "Arkose Labs",
    "BioCatch",
    "Castle",
    "Cloudflare Bot Management",
    "DataDome",
    "DataVisor",
    "Deduce",
    "Featurespace",
    "Feedzai",
    "Fingerprint",
    "Forter",
    "HUMAN Security",
    "Kount",
    "PerimeterX",
    "Riskified",
    "Shape Security",
    "Sift",
    "Socure",
    "ThreatMetrix",
    "TransUnion TruValidate",

    # --- Cloud Infrastructure Entitlement Management (CIEM) ---
    "Authomize",
    "Britive",
    "CloudKnox",
    "CrowdStrike CIEM",
    "Microsoft Entra Permissions",
    "Orca CIEM",
    "Permiso",
    "Sonrai CIEM",
    "Wiz CIEM",
    "Zilla Security",

    # --- Secure File Transfer / MFT ---
    "Accellion",
    "Axway",
    "Citrix ShareFile",
    "GoAnywhere MFT",
    "Kiteworks",
    "MOVEit",
    "Progress MOVEit",

    # --- Governance / Risk Quantification ---
    "Axio",
    "BitSight Technologies",
    "Brinqa",
    "C2M2",
    "Kovrr",
    "Panorays",
    "ProcessBolt",
    "RiskLens",
    "Safe Security",
    "SecurityScorecard Platform",
    "UpGuard BreachSight",

    # --- Third-Party Risk Management ---
    "Black Kite",
    "CyberGRX",
    "OneTrust Vendorpedia",
    "Panorays TPRM",
    "Prevalent",
    "ProcessUnity TPRM",
    "RiskRecon",
    "SecurityScorecard TPRM",
    "Whistic",

    # --- Security Questionnaire Automation ---
    "Conveyor Questionnaire",
    "Loopio",
    "OneTrust Athena",
    "Responsive",
    "SafeBase Trust Center",
    "Vanta Questionnaire",
    "Whistic Questionnaire",

    # --- Open Source Security Tools ---
    "Burp Suite Community",
    "ClamAV",
    "Fail2Ban",
    "Kali Linux",
    "Metasploit Framework",
    "Nmap",
    "OpenSCAP",
    "OpenVAS Scanner",
    "OSSEC HIDS",
    "Snort",
    "Suricata",
    "Wireshark",
    "YARA",

    # --- AI Security / LLM Security ---
    "Arthur AI",
    "CalypsoAI",
    "Cranium AI",
    "DeepKeep",
    "HiddenLayer",
    "LLM Guard",
    "Noma Security",
    "Protect AI",
    "Rebuff AI",
    "Robust Intelligence",

    # --- Security Service Edge ---
    "Citrix SSE",
    "Forcepoint SSE",
    "Netskope SSE",
    "Palo Alto Prisma SASE",
    "Skyhigh SSE",
    "Zscaler SSE",

    # --- Digital Forensics / Incident Response ---
    "Belkasoft",
    "Binalyze",
    "Cado Security",
    "Cellebrite",
    "CrowdStrike Falcon Forensics",
    "Exterro",
    "Magnet Forensics",
    "OpenText EnCase",
    "Oxygen Forensics",
    "Paraben",
    "Volatility",
    "X-Ways Forensics",

    # --- Secure Communications ---
    "Abnormal Security ICES",
    "BlackBerry SecuSUITE",
    "Element (Matrix)",
    "Keybase",
    "Mimecast S2",
    "PreVeil",
    "Signal Enterprise",
    "Silent Circle",
    "Wickr",
    "Wire",

    # --- API Gateway / API Management ---
    "Apigee",
    "AWS API Gateway",
    "Azure API Management",
    "Kong Gateway",
    "MuleSoft",
    "Tyk",

    # --- DSPM (Data Security Posture Management) ---
    "BigID DSPM",
    "Cyera DSPM",
    "Dig Security DSPM",
    "Flow Security",
    "Normalyze",
    "Polar Security",
    "Sentra",
    "Symmetry Systems",
    "Varonis DSPM",
    "Wiz DSPM",

    # --- Cyber Insurance ---
    "At-Bay",
    "Coalition",
    "Corvus Insurance",
    "Cowbell Cyber",
    "Resilience Cyber Insurance",

    # --- Miscellaneous / Multi-Category ---
    "Broadcom",
    "Dell Technologies",
    "Google Cloud Security",
    "HackerOne Bounties",
    "Hewlett Packard Enterprise",
    "Herjavec Group",
    "Kyndryl",
    "Leidos",
    "ManageEngine",
    "Micro Focus",
    "Microsoft Security",
    "NCC Group",
    "Palo Alto Networks Unit 42",
    "Rapid7 Platform",
    "Raytheon Cyber",
    "ReliaQuest",
    "RSA Security",
    "Schneider Electric",
    "SecureAuth",
    "SecureWorks",
    "Siemens",
    "Sophos Central",
    "Symantec",
    "Thales",
    "Unisys Stealth",
    "Upstream Security",
    "Verint",
    "Webroot",
    "Zimperium MAPS",

    # --- Security Operations / SOC Platforms ---
    "Blumira",
    "Chronicle SecOps",
    "Cyware Fusion",
    "InsightIDR",
    "LogicHub SOAR+",
    "ReliaQuest GreyMatter",
    "Respond Software",
    "Revelstoke",
    "SecOps Solution",
    "Siemplify SOAR",

    # --- Phishing Simulation ---
    "GoPhish",
    "King Phisher",
    "Lucy Security",
    "PhishER",
    "Proofpoint Phishing Simulation",
    "Sophos Phish Threat",

    # --- Network Access Control (NAC) ---
    "Aruba ClearPass",
    "Cisco ISE",
    "Extreme Networks",
    "Forescout NAC",
    "FortiNAC",
    "Portnox",
    "Pulse Secure",

    # --- DDoS Protection ---
    "Akamai Prolexic",
    "AWS Shield",
    "Azure DDoS Protection",
    "Cloudflare DDoS",
    "Corero",
    "F5 Silverline",
    "Imperva DDoS",
    "Neustar DDoS",
    "Radware DDoS",
    "Sucuri",

    # --- Quantum-Safe / Post-Quantum ---
    "ISARA",
    "PQShield",
    "Quantinuum",
    "QuSecure",
    "SandboxAQ",

    # --- SBOM (Software Bill of Materials) ---
    "Anchore SBOM",
    "FOSSA SBOM",
    "Manifest Cyber",
    "Mend SBOM",
    "Rezilion SBOM",
    "SPDX",
    "Tidelift SBOM",

    # --- Insider Threat ---
    "Code42 Incydr",
    "DTEX InTERCEPT",
    "Ekran System Insider",
    "Gurucul",
    "ObserveIT",
    "Proofpoint ITM",
    "Securonix UEBA",
    "Teramind Insider Threat",
    "Veriato",

    # --- Secure Remote Access / VPN ---
    "Check Point VPN",
    "Cisco AnyConnect",
    "Citrix Gateway",
    "F5 Access",
    "Fortinet FortiClient",
    "GlobalProtect",
    "Ivanti Connect Secure",
    "NordLayer",
    "OpenVPN",
    "Palo Alto GlobalProtect",
    "WireGuard",

    # --- Kubernetes / Container Runtime Security ---
    "Aqua kube-bench",
    "Calico",
    "Cilium",
    "Falco Runtime",
    "KubeLinter",
    "Kubescape",
    "Mondoo",
    "Prisma Cloud Container",
    "StackRox",
    "Sysdig Runtime",
    "Tigera",
    "Wiz Runtime Sensor",

    # --- Security for SaaS ---
    "Adaptive Shield",
    "AppOmni",
    "DoControl",
    "Grip Security",
    "Nudge Security",
    "Obsidian Security",
    "Reco",
    "SaaS Alerts",
    "Savvy Security",
    "SpinOne",
    "Suridata",
    "Valence Security",
    "Wing Security",

    # --- Unified Endpoint Security ---
    "Absolute Resilience",
    "CrowdStrike Falcon Go",
    "Microsoft Defender for Business",
    "Sophos Central Endpoint",
    "ThreatLocker",

    # --- Infrastructure as Code (IaC) Security ---
    "Accurics",
    "Bridgecrew Checkov IaC",
    "Checkov",
    "Indeni Cloudrail",
    "KICS",
    "Snyk IaC",
    "Terraform Sentinel",
    "tfsec",

    # --- Cloud Workload Protection ---
    "Aqua Cloud Native Security",
    "CrowdStrike Cloud Security",
    "Deep Security",
    "Illumio CloudSecure",
    "Kaspersky Hybrid Cloud Security",
    "Trend Micro Cloud One",

    # --- Security Analytics / UEBA ---
    "Adlumin",
    "Exabeam Advanced Analytics",
    "Gurucul UEBA",
    "Microsoft Sentinel UEBA",
    "Securonix Next-Gen SIEM",
    "Splunk UBA",

    # --- Code Signing ---
    "DigiCert Code Signing",
    "Entrust Code Signing",
    "Keyfactor SignServer",
    "SignPath",
    "Venafi CodeSign Protect",

    # --- Hardware Security ---
    "Thales Luna Network HSM",
    "Utimaco",
    "YubiKey",
    "Yubico",

    # --- MSSP / SOCaaS ---
    "Alert Logic",
    "Avertium",
    "Critical Start",
    "Deepwatch",
    "Nuspire",
    "Open Systems",
    "Perch Security",
    "UnderDefense",
    "Vigilance MDR",

    # --- Penetration Testing Platforms ---
    "Core Security",
    "Immuniweb",
    "Intruder",
    "Invicti Acunetix",
    "Pentest-Tools.com",
    "Qualys WAS",
    "Tenable.io WAS",

    # --- Cloud Access Security ---
    "Ciphercloud",
    "McAfee MVISION Cloud",
    "Microsoft Cloud App Security",
    "Skyhigh CASB",

    # --- Security Ratings ---
    "BitSight Security Ratings",
    "RiskRecon Ratings",
    "SecurityScorecard Ratings",
    "UpGuard Security Ratings",

    # --- Threat Hunting ---
    "Cyborg Security",
    "EclecticIQ Platform",
    "KELA",
    "Polarity",
    "Team Cymru",
    "ThreatBook",

    # --- Risk-Based Vulnerability Management ---
    "Brinqa Platform",
    "Kenna Security",
    "NopSec",
    "Nucleus Security",
    "Vulcan Cyber",

    # --- OT-specific ---
    "Bayshore Networks",
    "Fortinet FortiGate Rugged",
    "Honeywell Forge",
    "Phoenix Contact",
    "Tofino Security",

    # --- Automotive Cybersecurity ---
    "Argus Cyber Security",
    "C2A Security",
    "Karamba Security",
    "PlaxidityX",
    "Upstream Security Automotive",

    # --- Space / Satellite Cybersecurity ---
    "SpiderOak",

    # --- Compliance-Specific ---
    "A-LIGN",
    "Coalfire Compliance",
    "Compyl",
    "Cority",
    "RegScale",
    "RSAM",
    "TrustMAPP",
    "ZenComply",
]

# Deduplicate and sort
VENDORS = sorted(set(VENDORS), key=str.casefold)
